config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  resources :tasks, except: %i[show] do
    collection do
      get :export_csv
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

# class Task < ApplicationRecord
class Task < ApplicationRecord
  validates :description, presence: true
  validates :done, inclusion: { in: [true, false] }

  belongs_to :parent, class_name: 'Task', optional: true

  has_many :sub_tasks, class_name: 'Task', foreign_key: :parent_id, dependent: :destroy

  scope :only_parents, -> { where(parent_id: nil) }

  def parent?
    parent_id.nil?
  end

  def sub_task?
    !parent?
  end

  # Voltar na aula:
  # Criando aplicacoes reais - Gerenciador de tarefas (parte 4)
  # O que sera criada a seguir nao e recomendado.
  # O correto seria estar em um decorator
  def symbol
    case status
    when 'pending'  then '»'
    when 'done'     then '✓'
    when 'expired'  then '✕'
    end
  end

  def css_color
    case status
    when 'pending'  then 'primary'
    when 'done'     then 'success'
    when 'expired'  then 'danger'
    end
  end

  private

  def status
    return 'done' if done?

    due_date.past? ? 'expired' : 'pending'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# class ApplicationController
class ApplicationController < ActionController::Base
  before_action :authenticate

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == Rails.application.credentials.authentication[:username] &&
        password == Rails.application.credentials.authentication[:password]
    end
  end
end

app/controllers/concerns/exportable.rb
# frozen_string_literal: true

require 'csv'

module Exportable
  extend ActiveSupport::Concern

  def export_csv
    headers = ['ID', 'Descrição', 'Finalizado', 'ID da tarefa pai', 'Criada em', 'Atualizado em']

    csv = CSV.generate(write_headers: true, headers: headers) do |row|
      Task.all.each do |task|
        row << [task.id, task.description, task.done? ? 'Sim' : 'Não', task.parent_id, task.created_at, task.updated_at]
      end
    end

    send_data csv, type: 'text/csv; charset=utf-8; header=present',
                   disposition: 'attachment; filename=tarefas.csv'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include Exportable
  before_action :set_task, only: %i[show edit update destroy]

  # index retorna uma colecao dos registros importantes
  # para essa pagina
  def index
    # O @varivail quer dizer que ela estara disponivel nas views.
    @tasks = Task.only_parents.order(:due_date)
  end

  # new cria um novo registro que depois ira persistir no db com o create.
  def new
    @task = Task.new
  end

  # O edit e o new tem views parecidas
  def edit
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_path, notice: 'Tarefa foi criada com sucesso.'
    else
      flash.now[:alert] = @task.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'Tarefa foi atualizada com sucesso.'
    else
      flash.now[:alert] = @task.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Tarefa foi removida com sucesso.'
  end

  private

  # set evita a repeticao do codigo nos metodos.
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :due_date, :done, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt'>
  <head>
    <title>Gerenciador de Tarefas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class='d-flex h-100 align-items-center justify-content-center row bg'>
      <main class='col-11 col-md-10 col-lg-8 shadow-lg p-5 mb-5 bg-white rounded'>
        <% flash.each do |type, message| %>
          <div class='alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show' role='alert'>
            <%= message %>
            <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
              <span aria-hidden='true'>&times;</span>
            </button>
          </div>
        <% end %>

      <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <%= form.hidden_field :parent_id,
    value: task.parent_id || params[:parent_id] %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :done, class: 'form-check-input' %>
    <%= form.label :done, class: 'form-check-label' %>
  </div>

  <%= form.submit class: 'btn btn-primary',
    data: { disable_with: 'Salvando...' } %>

  <%= link_to 'Cancelar', tasks_path, class: 'btn btn-secondary text-white' %>

<% end %>

app/views/tasks/_table_row.html.erb
<tr class='<%= task.parent? ? 'border-top' : '' %> '>
  <td class='<%= task.sub_task? ? 'pl-5' : '' %> '>
    <span class='text-<%= task.css_color %> pr-1'><%= task.symbol %></span>
    <% if task.done? %>
      <s class='text-muted'><%= task.description %></s>
    <% else %>
      <%= task.description %>
    <% end %>
  </td>


  <td><%= l task.due_date %></td>

  <td class='text-right pr-0'>
    <% if task.parent? %>
      <%= link_to '+ Sub-tarefa', new_task_path(parent_id: task.id),
        class: 'btn btn-success btn-sm' %>
    <% end %>

    <%= link_to 'Editar', edit_task_path(task),
      class: 'btn btn-secondary btn-sm' %>

    <%= link_to 'Apagar', task, method: :delete,
      class: 'btn btn-danger btn-sm',
      data: { confirm: 'Tem certeza?'} %>
  </td>
</tr>

app/views/tasks/edit.html.erb
<h1 class='display-4'>
  Editar <%= @task.parent? ? 'Tarefa' : 'Sub-tarefa' %>
</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class='row mb-2'>
  <div class='col-8'>
    <h1 class='display-4'>Tarefa</h1>
  </div>

  <div class='col-4 mt-4 text-right'>
    <%= link_to '+ Tarefa', new_task_path, class: 'btn btn-success' %>
    <%= link_to 'Exportar csv', export_csv_tasks_path, class: 'btn btn-info' %>
  </div>
</div>

<% if @tasks.any?%>
  <table class='table table-borderless'>
    <thead>
      <tr>
        <th>Descrição</th>
        <th>Prazo</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <%= render 'table_row', task: task %>

        <% task.sub_tasks.order(:due_date).each do |sub_task| %>
          <%= render 'table_row', task: sub_task %>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Nenhuma tarefa foi cadastrada ainda.</p>
<% end %>

app/views/tasks/new.html.erb
<h1 class='display-4'>
  Nova <%= params[:parent_id].present? ? 'Sub-tarefa' : 'Tarefa' %>
</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>Done:</strong>
  <%= @task.done %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>